# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y libc6-dev gcc

# Copy the current directory contents into the container at /app
COPY . /app/

# Create a virtual environment and activate it
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt

# Expose port 8080 for uwsgi to bind to
EXPOSE 8080

# Command to run your application using uwsgi
CMD ["uwsgi", "--ini", "uwsgi.ini"]
