# Use a lightweight base image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Install system dependencies
RUN apt-get update && \
    apt-get install -y build-essential libpcre3 libpcre3-dev

# Copy the application files into the container
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port that uWSGI will run on
EXPOSE 5000

CMD ["uwsgi", "--http", ":5000", "--wsgi-file", "main.py", "--callable", "app"]
